services:
  tarantool-app:
    build: .
    container_name: kv-app
    environment:
      APP_ENV: "${APP_ENV:-local}"
      APP_HOST: "${APP_HOST:-localhost}"
      APP_PORT: "${APP_PORT:-8081}"
      STORAGE_HOST: "tarantool-storage"
      STORAGE_PORT: "${STORAGE_PORT:-3301}"
      STORAGE_USERNAME: "storage"
      STORAGE_PASSWORD: "sesame"
    ports:
      - 8081:8081
    depends_on:
      tarantool-storage:
        condition: service_healthy
    networks:
      - tarantool

  tarantool-storage:
    image: tarantool/tarantool:3@sha256:294387c35a6120c6d881a3e1ccc174938c94afbe744834e6d500f28063c883f2
    container_name: kv-storage
    environment:
      TT_INSTANCE_NAME: "instance001"
      TT_CONFIG: "/opt/tarantool/tarantool_config.yaml"
      TT_IPROTO_LISTEN: '[ {"uri":"${STORAGE_PORT:-3301}"} ]'
    volumes:
      - tarantool_data:/var/lib/tarantool
      - ./config/init.lua:/opt/tarantool/init.lua
      - ./config/tarantool_config.yaml:/opt/tarantool/tarantool_config.yaml
    healthcheck:
      test: ["CMD-SHELL", "status"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - tarantool

volumes:
  tarantool_data:
    name: tarantool_data_vol

networks:
  tarantool:
    driver: bridge
