services:
  tarantool-app:
    build: .
    container_name: tt-kv-app
    env_file:
      - .env
    links:
      - "tarantool-storage:${TT_HOST}"
    volumes:
      - type: bind
        source: ./config/app_config.yaml
        target: /app_config.yaml
        read_only: true
    ports:
      - "${HTTP_PORT:-8080}:8080"
    depends_on:
      tarantool-storage:
        condition: service_healthy
    networks:
      - tarantool

  tarantool-storage:
    image: tarantool/tarantool:3.3.1@sha256:294387c35a6120c6d881a3e1ccc174938c94afbe744834e6d500f28063c883f2
    container_name: tt-kv-storage
    env_file:
      - .env
    volumes:
      - type: volume
        source: tarantool_data
        target: /var/lib/tarantool
      - type: bind
        source: ./config
        target: /opt/tarantool
        read_only: true
    command: tarantool --name "instance001" --config /opt/tarantool/tt_config.yaml
    healthcheck:
      test: ["CMD-SHELL", "status"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - tarantool

  swagger-ui:
    image: swaggerapi/swagger-ui@sha256:24b71463bed4551c57b9ef9c8a395008e40a45dcd37bc594aaf29474c592bf58
    container_name: swagger-ui
    environment:
      SWAGGER_JSON: /openapi.yaml
      BASE_URL: /swagger
    volumes:
      - type: bind
        source: ./docs/swagger.yaml
        target: /openapi.yaml
    ports:
      - "8081:8080"
    networks:
      - tarantool
    depends_on:
      - tarantool-app

volumes:
  tarantool_data:
    name: tarantool_data

networks:
  tarantool:
    driver: bridge
