---
app:
  name: "tarantool-app"
  version: "0.1.0"
  file: "tarantool_storage_init.lua"

log:
  level: "debug"

http:
  port: "8080"

storage:

credentials:
  users:
    storage:
      password: sesame
      privileges:
      - permissions: [ read, write ]
        spaces: [ kv_storage ]

groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001: {}
