---
# Deployment environment: local, prod.
app_env: "local"

# Storage uri and connection credentials.
storage:
  storage_host: "instance001"
  storage_port: "3301"
  credentials:
    user: "storage"
    password: "sesame"

# App HTTP server uri.
http_server:
  app_host: "localhost"
  app_port: "8081"
  timeout: 5s
  idle_timout: 60s
